/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class tampilanpegawai extends javax.swing.JFrame {

    /**
     * Creates new form pegawai
     */
    public tampilanpegawai(String nama) {
        initComponents();
        user.setText(nama);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
    }
    public JLabel getExit() {
        return exit;
    }
    public void addlistener(MouseListener e){
        exit.addMouseListener(e);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gaji = new javax.swing.JLabel();
        jeniskelamin = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jabatan = new javax.swing.JLabel();
        agama = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(583, 450));
        jPanel1.setLayout(null);

        gaji.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gaji.setForeground(new java.awt.Color(255, 255, 0));
        gaji.setText("gaji :");
        gaji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(gaji);
        gaji.setBounds(120, 280, 310, 20);

        jeniskelamin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jeniskelamin.setForeground(new java.awt.Color(255, 255, 0));
        jeniskelamin.setText("jenis kelamin : ");
        jeniskelamin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jeniskelamin);
        jeniskelamin.setBounds(120, 160, 310, 20);

        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 0));
        email.setText("email :");
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(email);
        email.setBounds(120, 190, 320, 20);

        jabatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jabatan.setForeground(new java.awt.Color(255, 255, 0));
        jabatan.setText("jabatan :");
        jabatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jabatan);
        jabatan.setBounds(120, 130, 280, 20);

        agama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        agama.setText("agama :");
        agama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(agama);
        agama.setBounds(120, 220, 330, 20);

        alamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alamat.setText("alamat :");
        alamat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(alamat);
        alamat.setBounds(120, 250, 310, 20);

        nama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 0));
        nama.setText("nama");
        nama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(nama);
        nama.setBounds(120, 100, 290, 20);

        user.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        user.setForeground(new java.awt.Color(51, 204, 0));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon.png"))); // NOI18N
        jPanel1.add(user);
        user.setBounds(10, 13, 213, 48);

        exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 204, 0));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N
        exit.setText("EXIT");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(exit);
        exit.setBounds(446, 13, 112, 35);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/backgroundmain.jpg"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(583, 390));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 583, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agama;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel email;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel gaji;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jabatan;
    private javax.swing.JLabel jeniskelamin;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
    public void settext(String nm,String jbtn, String jk, String emaile, String agm, String almt, String gj){
        nama.setText("nama : "+nm);
        jabatan.setText("jabatan : "+jbtn);
        jeniskelamin.setText("jenis kelamin : "+jk);
        email.setText("email : "+emaile);
        agama.setText("agama : "+agm);
        alamat.setText("alamat : "+almt);
        gaji.setText("gaji : "+gj);
    }
}
